config/routes.rb
Rails.application.routes.draw do
  
  resources :organisations
  resources :shifts do
    match "destroy_user_shifts" => "shifts#destroy_user_shifts", :as => :destroy_user_shifts, via: :get
  end
  resources :shifts
  resources :users do 
    match "join_organisation" => "users#join_organisation", :as => :join_organisation, via: :get
  end
  resources :users do 
    match "leave_organisation" => "users#leave_organisation", :as => :leave_organisation, via: :get
  end
  
  resources :users, only: [:index, :create, :update, :destroy, :joinOrganisation]
  
  get '/', to: 'sessions#new', as: 'root'
  
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  get '/signup', to: 'users#new', as:'signup'
  post '/signup', to: 'users#create'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  
  
end

app/models/organisation.rb
class Organisation < ApplicationRecord
    has_many :users
    has_many :shifts, through: :users, dependent: :destroy
    validates :name, presence: true
    validates :hourly_rate, presence: true
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: %i[ show edit update destroy ]

  
  def index
    @organisations = Organisation.all
  end

  
  def show
    @organisation = Organisation.find(params[:id])
  end

  
  def new
    @organisation = Organisation.new
  end

 
  def edit
  end

  
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to organisations_path }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to organisation_path(params[:id])}
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @organisation.destroy

    respond_to do |format|
      format.html { redirect_to organisations_url, notice: "Organisation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

   
    def organisation_params
      params.require(:organisation).permit(:name, :hourly_rate)
    end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_form.html.erb
<%= form_with(model: organisation) do |form| %>
 
  <%= form.label :name %>
  <%= form.text_field :name %><br>
  <%= form.label :hourly_rate %>
  <%= form.text_field :hourly_rate %><br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h2>Edit Organisation</h2>
<%= form_for @organisation do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :hourly_rate %>
<%= f.text_field :hourly_rate %><br>
<%= f.submit "Update Organisation"%>
<% end %>

<%= link_to 'Delete', @organisation, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back',  url_for(:back) %>

app/views/organisations/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Organisations</h2>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisations.each do |organisation| %>
      <tr>
      <td><%= organisation.name %></td>
      <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
        <td><%= link_to "Join", user_join_organisation_path(current_user, organisation_id: organisation.id) %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.erb
<h2>New Organisation</h2>
<%= render 'form', organisation: @organisation %>

<%= link_to 'Back',  url_for(:back) %>

app/views/organisations/show.html.erb
<h2>Organisation</h2>
<p id="notice"><%= notice %></p>
<% Organisation.find(params[:id]) %>
<%= "#{@organisation.name}" %>

<td><%= link_to 'View Shifts', shifts_path %></td> | <%= link_to 'Edit', edit_organisation_path(@organisation) %> | <%= link_to 'Leave', user_leave_organisation_path(current_user) %>