config/routes.rb
Rails.application.routes.draw do
  
  resources :organisations
  resources :shifts do
    match "destroy_user_shifts" => "shifts#destroy_user_shifts", :as => :destroy_user_shifts, via: :get
  end
  resources :shifts
  resources :users do 
    match "join_organisation" => "users#join_organisation", :as => :join_organisation, via: :get
  end
  resources :users do 
    match "leave_organisation" => "users#leave_organisation", :as => :leave_organisation, via: :get
  end
  
  resources :users, only: [:index, :create, :update, :destroy, :joinOrganisation]
  
  get '/', to: 'sessions#new', as: 'root'
  
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  get '/signup', to: 'users#new', as:'signup'
  post '/signup', to: 'users#create'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  
  
end

app/models/shift.rb
class Shift < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
    validates :start, presence: true
    validates :finish, presence: true
    validates :break_length, presence: true
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: %i[ show edit update destroy ]

  
  def index
    @shifts = Shift.all
  end

  
  def show
  end

  
  def new
    @shift = Shift.new
  end

  
  def edit
  end

  
  def create

    @start_time = params[:shift][:shift_date].to_s + ' ' + params[:shift][:start].to_s
    @finish_time = params[:shift][:shift_date].to_s + ' ' + params[:shift][:finish].to_s
    @shift = Shift.create(user_id:current_user.id, start:@start_time, finish:@finish_time, break_length:params[:shift][:break_length])

    respond_to do |format|
      if @shift.save
        format.html { redirect_to shifts_path}
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to shift_url(@shift), notice: "Shift was successfully updated." }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @shift.destroy

    respond_to do |format|
      format.html { redirect_to shifts_url, notice: "Shift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def self.destroy_user_shifts(params)
    Shift.where(user_id:params[:user_id]).delete_all
  end

  private
    
    def set_shift
      @shift = Shift.find(params[:id])
    end

    
    def shift_params
      params.require(:shift).permit(:user_id, :start, :finish, :break_length)
    end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= form_with(model: shift) do |form| %>
  <tr>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.label :shift_date_DD_MM_YYYY %>
  <%= form.text_field :shift_date%><br>
  <%= form.label :start_time %>
  <%= form.text_field :start%><br>
  <%= form.label :finish_time %>
  <%= form.text_field :finish %><br>
  <%= form.label :break_length %>
  <%= form.text_field :break_length %><br>
  </tr>
    <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<h2>Edit Shift</h2>
<%= form_for @shift do |f| %>
<%= f.label :shift_date %>
<%= f.text_field :shift_date %><br>
<%= f.label :start_time%>
<%= f.text_field :start %><br>
<%= f.label :finish_time %>
<%= f.text_field :finish %><br>
<%= f.label :break_length %>
<%= f.text_field :break_length %><br>
<%= f.submit "Update Organisation"%>
<% end %>

<%= link_to 'Delete', @shift, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back',  url_for(:back) %>

app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>



<h3>Shifts</h3>
<div>
<table>
    <tr>
      <th>Employee name</th> 
      <th>Shift date</th> 
      <th>Start time</th> 
      <th>Finish time</th> 
      <th>Break length</th> 
      <th>Hours worked</th>
      <th></th> 
      <th>Shift cost</th> 
    </tr>
    <% @shifts.each do |shift| %>
      <tr>
      <% if shift.user.organisation.id == current_user.organisation_id %>
      <td><%= shift.user.name %></td>
      <td><%= shift.start.to_date.strftime('%m/%d/%y') %></td>
      <td><%= shift.start.change(sec:shift.start.sec).strftime('%H:%M') %></td>
      <td><%= shift.finish.change(sec:shift.finish.sec).strftime('%H:%M') %></td>
      <td><%= shift.break_length %></td>
      <% break_minutes = (shift.break_length.to_i / 60.00) %>
      <td><%= TimeDifference.between(shift.finish.change(sec:shift.start.sec),shift.start.change(sec:shift.start.sec)).in_hours - break_minutes %><td>
      <% hours_worked = TimeDifference.between(shift.finish.change(sec:shift.start.sec),shift.start.change(sec:shift.start.sec)).in_hours - break_minutes %>
      <td><%= (hours_worked * 100).ceil/100.0 * (current_user.organisation.hourly_rate)  %><td>
      <% if current_user.id == shift.user_id %>
        <td><%= link_to 'Delete', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
      <%end%>
    <% end %>
  </table>
</div>

<br>

<%= link_to 'New Shift', new_shift_path %>
<%= link_to 'Back', organisation_path(current_user.organisation_id) %>

app/views/shifts/new.html.erb
<h3>New Shift</h3>

<%= render 'form', shift: @shift %>

<%= link_to 'Back',  shifts_path %>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>