config/routes.rb
Rails.application.routes.draw do
  
  resources :organisations
  resources :shifts do
    match "destroy_user_shifts" => "shifts#destroy_user_shifts", :as => :destroy_user_shifts, via: :get
  end
  resources :shifts
  resources :users do 
    match "join_organisation" => "users#join_organisation", :as => :join_organisation, via: :get
  end
  resources :users do 
    match "leave_organisation" => "users#leave_organisation", :as => :leave_organisation, via: :get
  end
  
  resources :users, only: [:index, :create, :update, :destroy, :joinOrganisation]
  
  get '/', to: 'sessions#new', as: 'root'
  
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  get '/signup', to: 'users#new', as:'signup'
  post '/signup', to: 'users#create'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkforceCode</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if current_user %>
    <h1>Adnat</h1>
    <tr>
    <td><% @user = User.find(session[:user_id]) %></td>
    <td><%= "Logged in as #{@user.name} "%></td>
    <td><%= link_to 'Logout', logout_path  %></td> | <td><%= link_to 'Edit Profile', edit_user_path(current_user.id) %></td>
    </tr>
  <% end %>
    <%= yield %>
  </body>
</html>